AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Lambda @ Edge demo. Execute in us-east-1
Parameters:
  BaseDomainName:
    Type: String
    Default: demo.redhead.cloud
    Description: Base domain name
  DistributionDomainName:
    Type: String
    Description: Domain name of the distribution
  LoadBalancerDomainName:
    Type: String
Resources:
  DistributionCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DistributionDomainName
      ValidationMethod: DNS
  DistributionRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${BaseDomainName}."
      Name: !Sub "${DistributionDomainName}."
      Type: A
      AliasTarget:
        DNSName: !GetAtt Distribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
  ViewerRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      CodeUri: ./viewer-requests/
      Description: !Sub "${AWS::StackName}-viewer-requests"
      FunctionName: !Sub "${AWS::StackName}-viewer-requests"
      Handler: "viewer-requests.handler"
      MemorySize: 128
      ReservedConcurrentExecutions: 500
      Runtime: python3.7
      Timeout: 1
      Role: !GetAtt ViewerRequestFunctionRole.Arn
  ViewerRequestFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
                - "edgelambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Description: !Sub "Role for ${AWS::StackName}-viewer-requests"
      ManagedPolicyArns:
        # Allows function to write logs to CloudWatch
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      MaxSessionDuration: 3600
      Path: "/"
      RoleName: !Sub "${AWS::StackName}-${AWS::Region}-viewer-requests"
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DistributionDomainName
        Origins:
          - Id: ALB
            DomainName: !Ref LoadBalancerDomainName
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
                - TLSv1.1
                - TLSv1
        Enabled: true
        DefaultRootObject: index.php
        HttpVersion: http2
        DefaultCacheBehavior:
          # Reminder: Lambda functions associated with a CloudFront distribution need to be created in the
          # us-east-1 region
          LambdaFunctionAssociations:
            - EventType: viewer-request
              LambdaFunctionARN: !Ref ViewerRequestFunction.Version
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0
          TargetOriginId: ALB
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all
          ViewerProtocolPolicy: allow-all
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref DistributionCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.1_2016